{% set name = "friendli-client" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendli_client-{{ version }}.tar.gz
  sha256: 500b38f8ffca92544755c5a4f683a22f856bc585b2614019189ec7d7d12f0243

build:
  entry_points:
    - friendli = friendli.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.6.1
    - pip
  run:
    - grpc-stubs >=1.53.0,<2.0.0
    - grpcio >=1.64.1,<2.0.0
    - grpcio-tools >=1.64.1,<2.0.0
    - python >=3.8.1,<4.0.0
    - requests >=2.0.0,<3.0.0
    - pyyaml >=6.0.1,<7.0.0
    - typer >=0.9.0,<0.10.0
    - rich >=12.2.0,<13.0.0
    - jsonschema >=4.17.3,<5.0.0
    - tqdm >=4.48.0,<5.0.0
    - pydantic >=1.9.0,<3
    - injector >=0.21.0,<0.22.0
    - protobuf >=5.26.1,<6.0.0
    - types-protobuf >=5.26.0,<6.0.0
    - httpx >=0.24.1,<0.25.0
    - fastapi >=0.104.0,<0.105.0
    - uvicorn >=0.23.2,<0.24.0
    - gql >=3.4.1,<4.0.0
    - packaging
  run_constrained:
    - transformers =4.41.2
    - h5py >=3.9.0,<4.0.0
    - einops >=0.6.1,<0.7.0
    - accelerate =0.21.0
    - datasets =2.16.0
    - peft =0.6.0
    - safetensors =0.4.1

test:
  imports:
    - friendli
  commands:
    - pip check
    - friendli --help
  requires:
    - pip

about:
  home: https://friendli.ai/
  summary: Client of Friendli Suite.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
