{% set name = "friendli-client" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/friendli_client-{{ version }}.tar.gz
  sha256: 682c53db8dfea411770a7b7993743a6606a966ad2cef6d444a45083fe34fac86

build:
  entry_points:
    - friendli = friendli.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.6.1
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - requests >=2.0.0,<3.0.0
    - pyyaml >=6.0.1,<7.0.0
    - typer >=0.9.0,<0.10.0
    - rich >=12.2.0,<13.0.0
    - jsonschema >=4.17.3,<5.0.0
    - tqdm >=4.48.0,<5.0.0
    - pydantic >=1.9.0,<3
    - injector >=0.21.0,<0.22.0
    - protobuf >=4.24.2,<5.0.0
    - types-protobuf >=4.24.0,<5.0.0
    - httpx >=0.24.1,<0.25.0
    - fastapi >=0.104.0,<0.105.0
    - uvicorn >=0.23.2,<0.24.0
    - gql >=3.4.1,<4.0.0
    - packaging
  run_constrained:
    - transformers =4.41.2
    - h5py >=3.9.0,<4.0.0
    - einops >=0.6.1,<0.7.0
    - accelerate =0.21.0
    - datasets =2.16.0
    - peft =0.6.0
    - safetensors =0.4.1

test:
  imports:
    - friendli
  commands:
    - pip check
    - friendli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://friendli.ai/
  summary: Client of Friendli Suite.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
